var ABC = 'qwertyuiopasdfghjklzxcvbnm';
ABC = ABC.toUpperCase().split("").sort();
export const radius = 20;
export const smallradius = 16;
export const medradius = 20;
export const qPadding = 5;
export const pageHeight = 1023;
export const maxQuestionHeight = 400;
export const initNQ = 7;
export const defaultBubbleValues = ['A', 'B', 'C'];
export const defaultQuestionValue = ['Is Rosi the Cutest?'];
export const defaultAnswers = ['Yes', 'No', 'Maybe'];
export const defaultQuestionHeight = 156.9;
export const headerHeight = 100;
export const primaryColor = '#3FA5D0';
export const secondaryColor = '#ffffff';
export default ABC;